add_executable(non_default_execution_space main.cpp)
target_link_libraries(non_default_execution_space PRIVATE kkf_warnings kkf_sanitizers Kokkos::kokkos kernel_extractor)

add_executable(non_default_execution_space_replay replay_main.cpp)
target_link_libraries(non_default_execution_space_replay PRIVATE kkf_warnings Kokkos::kokkos kernel_replayer)

add_replay_test(non_default_execution_space FALSE)
