kkf_add_test_executable(scalar_capture main.cpp)
target_link_libraries(scalar_capture PRIVATE kkf_sanitizers Kokkos::kokkos kernel_extractor)

kkf_add_test_executable(scalar_capture_replay replay_main.cpp)
target_link_libraries(scalar_capture_replay PRIVATE kkf_sanitizers Kokkos::kokkos kernel_replayer_sanitized)

add_replay_test(scalar_capture TRUE)
